steps:

# - id: 'build frontend'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'build',
#     '--tag=frontend', # use local registry for compatibility with local builds
#     '--tag=gcr.io/$PROJECT_ID/frontend',
#     '--cache-from=gcr.io/$PROJECT_ID/frontend:latest',
#     '--file=docker_compose/node/development/Dockerfile',
#     '.',
#   ]
#   waitFor: ['-'] # start immediately

# - id: 'push frontend'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'push',
#     'gcr.io/$PROJECT_ID/frontend'
#   ]
#   waitFor: ['build frontend']

# - id: 'build backend'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'build',
#     '--tag=backend', # use local registry for compatibility with local builds
#     '--tag=gcr.io/$PROJECT_ID/backend',
#     '--cache-from', 'gcr.io/$PROJECT_ID/backend:latest',
#     '--file=docker_compose/django/development/Dockerfile',
#     '.',
#   ]
#   waitFor: ['-'] # start immediately

# - id: 'push backend'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'push',
#     'gcr.io/$PROJECT_ID/backend'
#   ]
#   waitFor: ['build backend']

# - id: 'build db'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'build',
#     '--tag=postgres', # use local registry for compatibility with local builds
#     '--tag=gcr.io/$PROJECT_ID/postgres',
#     '--cache-from', 'gcr.io/$PROJECT_ID/postgres:latest',
#     '--file=docker_compose/postgres/Dockerfile',
#     '.',
#   ]
#   waitFor: ['-'] # start immediately

# - id: 'push db'
#   name: 'gcr.io/cloud-builders/docker'
#   args: [
#     'push',
#     'gcr.io/$PROJECT_ID/postgres'
#   ]
#   waitFor: ['build db']

# images:
#   [
#     'gcr.io/$PROJECT_ID/frontend',
#     'gcr.io/$PROJECT_ID/backend',
#     'gcr.io/$PROJECT_ID/postgres'
#   ]

- id: 'compose up'
  name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker-compose -f docker-compose-development.yml up -d 
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  # waitFor: ['build frontend','build backend', 'build db']

- id: 'integration tests'
  name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
  entrypoint: '/bin/bash'
  args: 
    - '-c'
    - |
      ### -r = retries; -i = interval; -k = keyword to search for ###
      ./test/test-connection.sh -r 20 -i 3 -u http://frontend:3000
  waitFor: ['compose up']