version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    container_name: postgres
    image: gcr.io/$PROJECT_ID/postgres
    build: ./docker_compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env

  frontend:
    container_name: frontend
    image: gcr.io/$PROJECT_ID/frontend
    build:
      context: .
      dockerfile: ./docker_compose/node/development/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    image: gcr.io/$PROJECT_ID/backend
    build:
      context: .
      dockerfile: ./docker_compose/django/development/Dockerfile
    command: /start.sh
    depends_on:
      - postgres
      - frontend
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres

networks:
    default:
        external:
            name: cloudbuild
